"""Experimental JAX-native, CIGALE-inspired SED graph.

This namespace is intentionally separate from the stable sedinfer backends.
It is importable without JAX installed; constructing or evaluating JAX objects
will raise a targeted ImportError if optional dependencies are missing.
"""

from .core import (
    GaussianPhotometricData,
    GaussianSpectralData,
    GaussianSpectroPhotometricData,
    JaxSedModel,
    ModuleSpec,
    SEDState,
    build_jax_sed_model,
    flat_lcdm_age_gyr_numpy,
)
from .bridge import restricted_cigale_modules_to_jaxcigale
from .cue import (
    CUE_THETA_BOUNDS,
    CueDerivedInputs,
    cue_logq_from_logu,
    cue_nebular_module,
    cue_theta12_to_public_package_theta,
    cue_theta_in_training_bounds,
    derive_cue_inputs_from_stellar_spectrum,
    reconstruct_cue_piecewise_lnu,
    toy_cue_emulator,
)
from .cue_port import CueBlockPort, CueJaxPort, CuePCAWeights, CueSpeculatorWeights
from .fsps_nebular import (
    FspsNebularContinuumTable,
    default_fsps_nebular_continuum_path,
    load_fsps_lyc_continuum_apply,
)
from .modules import (
    analytic_stellar_module,
    calzetti_attenuation_module,
    constant_sfh_cosmic_time_module,
    constant_sfh_module,
    continuity_sfh_cosmic_time_module,
    continuity_sfh_module,
    delayed_sfh_cosmic_time_module,
    delayed_sfh_module,
    dsps_stellar_module,
    exponential_sfh_cosmic_time_module,
    exponential_sfh_module,
    gordon16_rvfa_extinction_module,
    madau_igm_module,
    modified_starburst_attenuation_module,
    modified_blackbody_dust_module,
    nebular_emulator_module,
    no_nebular_module,
    powerlaw_sfh_cosmic_time_module,
    powerlaw_sfh_module,
    redshift_module,
    smc_screen_attenuation_module,
    two_temperature_dust_module,
)
from .parameters import (
    JaxParameterSpace,
    LogUniformJaxPrior,
    NormalJaxPrior,
    UniformJaxPrior,
    jax_parameter_space_from_sedinfer,
)
from .photometry import JaxFilterSet, integrate_maggies_numpy
from .spectroscopy import (
    bin_average_spectrum,
    gaussian_lsf_smooth_observed,
    model_spectrum_on_observed_pixels,
    pixel_edges_from_centers_numpy,
)
from .nuts import MapInitializationResult, NutsResult, find_map_initial_position, run_numpyro_nuts
from .ssp_data import (
    default_continuum_ssp_path,
    load_continuum_ssp_templates,
    require_continuum_ssp_path,
)

__all__ = [
    "GaussianPhotometricData",
    "GaussianSpectralData",
    "GaussianSpectroPhotometricData",
    "JaxFilterSet",
    "JaxParameterSpace",
    "JaxSedModel",
    "LogUniformJaxPrior",
    "MapInitializationResult",
    "ModuleSpec",
    "NormalJaxPrior",
    "NutsResult",
    "SEDState",
    "UniformJaxPrior",
    "build_jax_sed_model",
    "bin_average_spectrum",
    "CUE_THETA_BOUNDS",
    "CueDerivedInputs",
    "CueBlockPort",
    "CueJaxPort",
    "CuePCAWeights",
    "CueSpeculatorWeights",
    "FspsNebularContinuumTable",
    "analytic_stellar_module",
    "calzetti_attenuation_module",
    "constant_sfh_cosmic_time_module",
    "constant_sfh_module",
    "continuity_sfh_cosmic_time_module",
    "continuity_sfh_module",
    "cue_logq_from_logu",
    "cue_nebular_module",
    "cue_theta12_to_public_package_theta",
    "cue_theta_in_training_bounds",
    "derive_cue_inputs_from_stellar_spectrum",
    "delayed_sfh_cosmic_time_module",
    "delayed_sfh_module",
    "dsps_stellar_module",
    "exponential_sfh_cosmic_time_module",
    "exponential_sfh_module",
    "flat_lcdm_age_gyr_numpy",
    "find_map_initial_position",
    "gordon16_rvfa_extinction_module",
    "gaussian_lsf_smooth_observed",
    "integrate_maggies_numpy",
    "jax_parameter_space_from_sedinfer",
    "default_continuum_ssp_path",
    "default_fsps_nebular_continuum_path",
    "load_continuum_ssp_templates",
    "load_fsps_lyc_continuum_apply",
    "madau_igm_module",
    "model_spectrum_on_observed_pixels",
    "modified_blackbody_dust_module",
    "modified_starburst_attenuation_module",
    "nebular_emulator_module",
    "no_nebular_module",
    "pixel_edges_from_centers_numpy",
    "powerlaw_sfh_cosmic_time_module",
    "powerlaw_sfh_module",
    "redshift_module",
    "require_continuum_ssp_path",
    "reconstruct_cue_piecewise_lnu",
    "restricted_cigale_modules_to_jaxcigale",
    "run_numpyro_nuts",
    "smc_screen_attenuation_module",
    "toy_cue_emulator",
    "two_temperature_dust_module",
]
