"""Small helpers for DSPS SSP-table provenance.

The JAX-CIGALE experiments need stellar-continuum SSPs when a separate nebular
module such as Cue is applied.  DSPS' default FSPS v3.2 table includes FSPS
nebular emission, so using it upstream of Cue would derive the ionizing photon
budget from an already-processed spectrum and then add nebular emission again.
"""

from __future__ import annotations

import os
from pathlib import Path


CONTINUUM_SSP_ENV = "DSPS_CONTINUUM_SSP_FILE"
DEFAULT_DSPS_SSP_ENV = "DSPS_SSP_FILE"
CONTINUUM_SSP_FILENAMES = (
    "ssp_data_continuum_fsps_v3.2_lgmet_age.h5",
    "fsps_continuum_ssp_data.h5",
)
NEBULAR_INCLUDED_SSP_FILENAMES = (
    "ssp_data_fsps_v3.2_lgmet_age.h5",
)


def default_continuum_ssp_candidates() -> list[Path]:
    """Return likely local paths for a continuum-only FSPS/DSPS SSP table."""

    candidates: list[Path] = []
    env_path = os.environ.get(CONTINUUM_SSP_ENV)
    if env_path:
        candidates.append(Path(env_path))

    # File generated by examples/experimental_dsps_fsps_clock_diagnostic.py.
    candidates.append(Path("outputs/experimental_dsps_fsps_clock_diagnostic/fsps_continuum_ssp_data.h5"))

    # Common local DSPS data location used in the exploratory notebooks.
    candidates.append(Path("/Users/gregoire/Documents/New project 2/dsps_data/ssp_data_continuum_fsps_v3.2_lgmet_age.h5"))

    # If a user points DSPS_SSP_FILE at a continuum file, accept that too.
    ssp_env_path = os.environ.get(DEFAULT_DSPS_SSP_ENV)
    if ssp_env_path and looks_like_continuum_ssp_path(ssp_env_path):
        candidates.append(Path(ssp_env_path))

    unique: list[Path] = []
    for candidate in candidates:
        if candidate not in unique:
            unique.append(candidate)
    return unique


def default_continuum_ssp_path() -> Path:
    """Return the first existing continuum SSP candidate, or the preferred path.

    The returned path may not exist.  Callers that need the file immediately
    should run ``require_continuum_ssp_path`` before loading.
    """

    candidates = default_continuum_ssp_candidates()
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def looks_like_continuum_ssp_path(path: str | Path) -> bool:
    """Heuristic filename check for stellar-continuum FSPS SSP tables."""

    name = Path(path).name
    return "continuum" in name or name in CONTINUUM_SSP_FILENAMES


def looks_like_nebular_included_dsps_default(path: str | Path) -> bool:
    """Return True for DSPS' default nebular-included FSPS v3.2 SSP table."""

    return Path(path).name in NEBULAR_INCLUDED_SSP_FILENAMES


def require_continuum_ssp_path(path: str | Path, *, allow_nebular_included: bool = False) -> Path:
    """Validate that a DSPS SSP path is appropriate before adding Cue nebular.

    Parameters
    ----------
    path
        HDF5 SSP table path that will be passed to ``dsps.load_ssp_templates``.
    allow_nebular_included
        Diagnostic escape hatch.  Keep this False for scientific runs that add
        a separate nebular module.
    """

    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"DSPS continuum SSP file does not exist: {path}. "
            "Generate one with: "
            "SPS_HOME=/Users/gregoire/Work/FSPS "
            "PYTHONPATH=/Users/gregoire/Documents/Sedfitting/sedinfer-public "
            "/Users/gregoire/opt/anaconda3/envs/sbi_candide/bin/python "
            "examples/experimental_dsps_fsps_clock_diagnostic.py --stage make-ssp"
        )
    if allow_nebular_included:
        return path
    if looks_like_nebular_included_dsps_default(path):
        raise ValueError(
            f"{path.name} is DSPS' default FSPS v3.2 SSP table, which includes "
            "FSPS nebular emission.  Do not use it upstream of Cue/CLOUDY "
            "nebular emission because Q_H would be derived from an emergent, "
            "LyC-suppressed spectrum.  Use a continuum table such as "
            "ssp_data_continuum_fsps_v3.2_lgmet_age.h5 or "
            "outputs/experimental_dsps_fsps_clock_diagnostic/fsps_continuum_ssp_data.h5."
        )
    if not looks_like_continuum_ssp_path(path):
        raise ValueError(
            f"Cannot verify that {path.name} is a stellar-continuum SSP table. "
            "Rename the file to include 'continuum' or pass "
            "allow_nebular_included=True only for an explicit diagnostic."
        )
    return path


def load_continuum_ssp_templates(path: str | Path | None = None, *, allow_nebular_included: bool = False):
    """Load DSPS SSP templates after checking that they are continuum-only."""

    from dsps import load_ssp_templates

    checked_path = require_continuum_ssp_path(
        default_continuum_ssp_path() if path is None else path,
        allow_nebular_included=allow_nebular_included,
    )
    return load_ssp_templates(fn=str(checked_path))
